### ISSUE TITLE
TypeError: number_input() got an unexpected keyword argument 'help'

### ISSUE THREAD

**Issue by johnfelipe** [Jared-Chan/f1ml#1]
i put this command in a droplet from scratch

    apt update
    apt upgrade
    shutdown -r now

    apt install git python3-pip
    pip install streamlit

    git clone https://github.com/Jared-Chan/f1ml.git
    cd f1ml
    pip install -r requirements.txt
    streamlit run app.py

this is error:
    TypeError: number_input() got an unexpected keyword argument 'help'
    Traceback:
    File "/usr/local/lib/python3.8/dist-packages/streamlit/script_runner.py", line 332, in _run_script
        exec(code, module.__dict__)
    File "/root/f1ml/app.py", line 533, in <module>
        main()
    File "/root/f1ml/app.py", line 46, in main
        pred_laps = st.sidebar.number_input("Total number of laps", min_value=1, max_value=200, value=50, step=1, help='The model will predict up to this many laps.')

how solved?

**Comment by Jared-Chan** [comment]
Hi John,

It might be the case that you need to update your version of Streamlit, as someone suggested here: https://discuss.streamlit.io/t/help-argument-in-streamlit/11981/2

In any case, you can also remove that help message by changing line 46 in `app.py` 
from
 `    pred_laps = st.sidebar.number_input("Total number of laps", min_value=1, max_value=200, value=50, step=1, help='The model will predict up to this many laps.')`
to
 `    pred_laps = st.sidebar.number_input("Total number of laps", min_value=1, max_value=200, value=50, step=1)`

The page should still function fine.

I hope this helps.

**Comment by johnfelipe** [comment]
is a fresh installation, then is not possible update streamlit

https://paste.md-5.net/obevunaxet.rb

then im install requeriments

https://paste.md-5.net/qamugoxeyu.php

**Comment by Jared-Chan** [comment]
Have you tried to see if the website works after editing that line?

If it is an issue due to Streamlit itself then there is not much I can do.
