### ISSUE TITLE
2022?

### ISSUE THREAD

**Issue by vexersa** [Jared-Chan/f1ml#2]
Any plans to support 2022's season?

**Comment by Jared-Chan** [comment]
I don't have plans to do that any time soon, but if I do, I would retrain the model using data from [FastF1](https://theoehrly.github.io/Fast-F1/) and include parameters like car telemetry and position, tyre data, weather data, etc. 

Thanks for asking. If you are interested in doing something similar yourself and have any questions, I am happy to help.
