### ISSUE TITLE
question: do you have data from the races folder?

### ISSUE THREAD

**Issue by samhoppen** [Jared-Chan/f1ml#3]
Hey Jared, found your repo and trying to recreate something similar. Curious if you still have any of the files saved from the races folder that you eventually transformed into the races_npy files? Struggling to visualize how you transformed the original data and what specific features were in there. Would appreciate if you could share!

**Comment by Jared-Chan** [comment]
Hi Sam, I still have two versions of it, but it has been a while so I'm not sure which is the one you are looking for. 

[races.zip](https://github.com/Jared-Chan/f1ml/files/14335937/races.zip)
[races_v4.zip](https://github.com/Jared-Chan/f1ml/files/14335938/races_v4.zip)

I think they can also be reproduced from the .csv files in db/, though finding the right steps among my super well-documented notebooks may be a greater challenge than recreating them yourself. 

Hope this helps!

**Comment by samhoppen** [comment]
Yup, this is great! By chance do you have a Twitter or LinkedIn we could connect on that I could ask you a couple more questions? NBD if not, appreciate this repo nonetheless!

**Comment by Jared-Chan** [comment]
Sure, I'd love to. [This is my LinkedIn](https://www.linkedin.com/in/jared-chan-ca/).
